spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

security:
  cors:
    allowedOrigins: ${CORS_ALLOWED_ORIGINS}

server:
  tomcat:
    accesslog:
      enabled: true

log:
  single-line: true
